# This is the configuration file for SwerveLibrary. See the README for more in-depth information
# about how to fill this out.

[gyro]
template = "navx" # The type of gyro being used.
port-type = "I2C" # The type of port the navx is plugged into.
port = "kMXP" # The name of the port, as passed into the navx constructor.

[[modules]]
template = "team88.diff-swerve-2021.beta" # The template for the module.
location-inches = { x = -10.991, y = 12.491 } # The location of the module relative to it's center.
motors.0.can-id = 1 # The CAN ID of the first motor.
motors.1.can-id = 16 # The CAN ID of the second motor.
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 0
azimuth-sensor.offset = -10.286

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = -10.991, y = -12.491 }
motors.0.can-id = 2
motors.1.can-id = 3
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 1
azimuth-sensor.offset = -150.998

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = 10.991, y = -12.491 }
motors.0.can-id = 13
motors.1.can-id = 12
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 2
azimuth-sensor.offset = 64.687

[[modules]]
template = "team88.diff-swerve-2021.beta"
location-inches = { x = 10.991, y = 12.491 }
motors.0.can-id = 14
motors.1.can-id = 15
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-channel = 3
azimuth-sensor.offset = 168.133
