# Overall configurations
max-speed = 14.7

# Defining Designs

[gyro-designs.navx]

[motor-designs.falcon-500]
default-to-brake = true
inverted = false

[motor-designs.falcon-500.speed-pid]
kp = 0.1
ki = 0.0007
kd = 0
kf = 1

[position-sensor-designs.canifier-pwm]
ratio = 1

[module-designs.team88.diff-swerve-2021.beta]
differential-matrix = [
        [-0.041666666, 0.041666666],
        [0.09722222, 0.069444444]
    ]
final-wheel-ratio = 1.114

[module-designs.team88.diff-swerve-2021.beta.motors.0]
design = "falcon-500"
inverted = true

[module-designs.team88.diff-swerve-2021.beta.motors.1]
design = "falcon-500"
inverted = true

[module-designs.team88.diff-swerve-2021.beta.azimuth-sensor]
design = "canifier-pwm"
ratio = 0.002778

# Module and gyro configuration

[gyro]
design = "navx"
port = "MXP"

[[modules]]
design = "team88.diff-swerve-2021.beta"
location = { x = -12, y = 12 }
motors.0.falcon500.can-id = 16
motors.1.falcon500.can-id = 1
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 0

[[modules]]
design = "team88.diff-swerve-2021.beta"
location = { x = -12, y = -12 }
motors.0.falcon500.can-id = 2
motors.1.falcon500.can-id = 3
motors.1.falcon500.speed-pid.kf = 1.01
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 1

[[modules]]
design = "team88.diff-swerve-2021.beta"
location = { x = 12, y = -12 }
motors.0.falcon500.can-id = 12
motors.1.falcon500.can-id = 13
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 2

[[modules]]
design = "team88.diff-swerve-2021.beta"
location = { x = 12, y = 12 }
motors.0.falcon500.can-id = 14
motors.1.falcon500.can-id = 15
azimuth-sensor.can-id = 1
azimuth-sensor.pwm-id = 3
